package com.mercadolibre.dambetan01.model.user;

public enum EPermission {
    REGISTER_STOCK_PERMISSION(Constants.REGISTER_STOCK_PERMISSION),
    BUY_PRODUCT_PERMISSION(Constants.BUY_PRODUCT_PERMISSION),
    EDIT_PURCHASE_ORDER_PERMISSION(Constants.EDIT_PURCHASE_ORDER_PERMISSION),
    AUTHENTICATED_USER_PERMISSION(Constants.AUTHENTICATED_USER_PERMISSION),
    GET_PRODUCT_PURCHASE_ORDER_PERMISSION(Constants.GET_PRODUCT_PURCHASE_ORDER_PERMISSION),
    MODIFY_STOCK_PERMISSION(Constants.MODIFY_STOCK_PERMISSION),
    LIST_ALL_PRODUCT_PERMISSION(Constants.LIST_ALL_PRODUCT_PERMISSION),
    LIST_ALL_PRODUCT_PER_CATEGORY_PERMISSION(Constants.LIST_ALL_PRODUCT_PER_CATEGORY_PERMISSION),
    FIND_ALL_PRODUCT_BY_CATEGORY_AND_WAREHOUSE_PERMISSION(Constants.FIND_ALL_PRODUCT_BY_CATEGORY_AND_WAREHOUSE_PERMISSION),
    FIND_ALL_PRODUCT_STOCK_DUE_DATE_BY_SECTOR(Constants.FIND_ALL_PRODUCT_STOCK_DUE_DATE_BY_SECTOR),
    GET_PRODUCT_BY_WAREHOUSE_PERMISSION(Constants.GET_PRODUCT_BY_WAREHOUSE_PERMISSION);

    private final String value;

    EPermission(String value) {
        this.value = value;
    }

    public static class Constants {
        public static final String REGISTER_STOCK_PERMISSION = "REGISTER_STOCK_PERMISSION";
        public static final String BUY_PRODUCT_PERMISSION = "BUY_PRODUCT_PERMISSION";
        public static final String AUTHENTICATED_USER_PERMISSION = "AUTHENTICATED_USER_PERMISSION";
        public static final String EDIT_PURCHASE_ORDER_PERMISSION = "EDIT_PURCHASE_ORDER_PERMISSION";
        public static final String GET_PRODUCT_BY_WAREHOUSE_PERMISSION = "GET_PRODUCT_BY_WAREHOUSE_PERMISSION";
        public static final String GET_PRODUCT_PURCHASE_ORDER_PERMISSION = "GET_PRODUCT_PURCHASE_ORDER_PERMISSION";
        public static final String MODIFY_STOCK_PERMISSION = "MODIFY_STOCK_PERMISSION";
        public static final String LIST_ALL_PRODUCT_PERMISSION = "LIST_ALL_PRODUCT_PERMISSION";
        public static final String LIST_ALL_PRODUCT_PER_CATEGORY_PERMISSION = "LIST_ALL_PRODUCT_PER_CATEGORY_PERMISSION";
        public static final String FIND_ALL_PRODUCT_BY_CATEGORY_AND_WAREHOUSE_PERMISSION = "FIND_ALL_PRODUCT_BY_CATEGORY_AND_WAREHOUSE_PERMISSION";
        public static final String FIND_ALL_PRODUCT_STOCK_DUE_DATE_BY_SECTOR = "FIND_ALL_PRODUCT_STOCK_DUE_DATE_BY_SECTOR";
    }
}
