# Default properties file

spring:
  profiles:
    active: ${SCOPE_SUFFIX} # Comma-separated list of active profiles. Can be overridden by a command line switch.
  resources:
    add-mappings: false # Whether to enable default resource handling.
  mvc:
    throw-exception-if-no-handler-found: true # Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request.
  datasource:
    host: DB_MYSQL_DESAENV04_FINALPROJE_FINALPROJE_ENDPOINT
    db: finalproje
    username: finalproje_WPROD
    password: DB_MYSQL_DESAENV04_FINALPROJE_FINALPROJE_WPROD
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      sql: debug
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  compression:
    enabled: true # Whether response compression is enabled.
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed.
    min-response-size: 1024 # Minimum "Content-Length" value that is required for compression to be performed.

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  paths-to-match: /**
  packages-to-scan: com.mercadolibre.dambetan01.controller
  show-actuator: true
  swagger-ui:
    operations-sorter: alpha
    disable-swagger-default-url: true
    path: /swagger-ui.html

app:
  title: projeto-final-bootcamp-gabriel
  description: @project.description@
  version: @project.version@